// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe2ZexsUcK4zQx72kXYovRT1DeaQ4yIWc',
    appId: '1:979616360741:web:29a5f9fe75f7e2f68692cc',
    messagingSenderId: '979616360741',
    projectId: 'mensagem-2435d',
    authDomain: 'mensagem-2435d.firebaseapp.com',
    databaseURL: 'https://mensagem-2435d-default-rtdb.firebaseio.com',
    storageBucket: 'mensagem-2435d.appspot.com',
    measurementId: 'G-F87SE6YH65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANIaFMX9nsMoAUUmJEt9TE07vo2_kEkYs',
    appId: '1:979616360741:android:de162b1e70bb7b978692cc',
    messagingSenderId: '979616360741',
    projectId: 'mensagem-2435d',
    databaseURL: 'https://mensagem-2435d-default-rtdb.firebaseio.com',
    storageBucket: 'mensagem-2435d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Qqz1_DWYF-lcn3M_1hfoNzbHJFjyj2A',
    appId: '1:979616360741:ios:42f4791feb899af68692cc',
    messagingSenderId: '979616360741',
    projectId: 'mensagem-2435d',
    databaseURL: 'https://mensagem-2435d-default-rtdb.firebaseio.com',
    storageBucket: 'mensagem-2435d.appspot.com',
    iosBundleId: 'comum.example.talkHubVs2',
  );
}
